### ISSUE TITLE
INFOGRAFIA DE LAS LIBRERIAS

### ISSUE THREAD

**Issue by MariaJose-10** [SistemasTecTlaxiaco/infografia-de-las-librerias-MariaJose-10#3]
[INFOGRAFIA_LL MARIA JOSE.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-MariaJose-10/files/8343216/INFOGRAFIA_LL.MARIA.JOSE.pdf)

**Comment by RaelRGB** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
